fix(git-qclone): user->owner

diff --git a/scripts/bin/git-qclone b/scripts/bin/git-qclone
--- a/scripts/bin/git-qclone
+++ b/scripts/bin/git-qclone
@@ -4,7 +4,7 @@
 arg=$1
 
 prefix=$(git config qclone.prefix)
-user=$(git config qclone.user)
+owner=$(git config qclone.owner)
 suffix=$(git config qclone.suffix)
 
 # Set default values
@@ -19,10 +19,10 @@ fi
 
 # Only a repo was provided
 
-if [[ -z "$user" ]]; then
-	echo "ERROR: user not provided in either git config or argument" >&2
+if [[ -z "$owner" ]]; then
+	echo "ERROR: owner not provided in either git config or argument" >&2
 	exit 1
 fi
 
 set -x
-exec git clone "${prefix}${user}/${arg}${suffix}"
+exec git clone "${prefix}${owner}/${arg}${suffix}"
